### PR TITLE
fix: extract mongo too, return proper error

### LINKED ISSUE #13: Can't start memmongo with replicaset - panic with wrong error returned
When trying to start mongo with a replica set, we are getting a panic instead of an error due to:

https://github.com/tryvium-travels/memongo/blob/a32a48fdd6719f0718c73c2a0428b09363a29110/memongo.go#L176-L181

Where `err` is erroneously returned instead of `err2`.

But the actual problem lies a few lines above, where the existence of `mongo` cli tools is assumed to exist on the $PATH:
https://github.com/tryvium-travels/memongo/blob/a32a48fdd6719f0718c73c2a0428b09363a29110/memongo.go#L167-L171

### PR DESCRIPTION
**Pull request by shlomi-dr**
Return proper error and extract mongo binary itself for replica-set to work

fixes #13

### CODE REVIEW

File: mongobin/getOrDownload.go [hunk 1]
```diff
@@ -150,10 +166,7 @@ func GetOrDownloadMongod(urlStr string, cachePath string, logger *memongolog.Log
 
 		return "", fmt.Errorf("error writing mongod binary from %s to %s: %s", mongodTmpFile.Name(), mongodPath, renameErr)
 	}
-
-	logger.Infof("finished downloading mongod to %s in %s", mongodPath, time.Since(downloadStartTime).String())
-
-	return mongodPath, nil
+	return "", nil
```
Comment (saniales) [inline mongobin/getOrDownload.go]: What is the meaning of this line? You are basically making the whole function call useless, 
if this was intentional explain this change, otherwise revert to the old line 

```
return mongodPath, nil
```

File: mongobin/getOrDownload.go [hunk 2]
```diff
@@ -98,11 +101,24 @@ func GetOrDownloadMongod(urlStr string, cachePath string, logger *memongolog.Log
...
+			}
+			if fileCount >= maxFilesCount {
+				break
+			}
 		}
 	}
 
+	logger.Infof("finished downloading mongod to %s in %s", mongodPath, time.Since(downloadStartTime).String())
+
+	return mongodPath, nil
```
Comment (saniales) [inline mongobin/getOrDownload.go:118]: Clarify why mongodPath is got in this way rather than using saveFile

perhaps it is better for the saveFile function to just return error now? instead of (string, error)

**Review by saniales — CHANGES_REQUESTED** [review]
See comments

File: mongobin/getOrDownload.go (hunk 2 above)
Comment (shlomi-dr) [reply mongobin/getOrDownload.go:118]: This PR is making the least amount of changes to fix the bugs pointed out in #13. I did not change any semantics. This means that this function returns exactly what it returned before this PR, which is the full path of `mongodPath`, that is computed by the line `mongodPath := path.Join(dirPath, "mongod")` above (43) and remains a constant regardless of execution path (as long as no error is returned). 

`saveFile` function is simply an extraction of the original code, which exclusively handled extracting `mongod` alone without also extracting the needed `mongo`. Reason why we can't simply return the result of `saveFile` is that it must be called twice now, once for each file we would like to extract. I agree, `saveFile` should simply return an error now.

In any case, this is simply the minimum change required for this library to extract all required files, and intended as a workaround for my teams until a more proper PR is created and merged.

File: mongobin/getOrDownload.go (hunk 1 above)
Comment (shlomi-dr) [reply mongobin/getOrDownload.go]: No semantics were changed in this PR. This piece is simply a  refactor aimed and retaining the exact same semantics from earlier. This line does not make the function call useless at all, since the function is side-effecting by means of extracting the actual file to the filesystem at the right location. I think you may have mistaken this return value to be that of `GetOrDownloadMongod`, but it is not, it is of `saveFile`.

This first return value is used exclusively at line 108, for returning when the error is returned. I agree, we could change this to return just the error, as the first value is unused.

Comment (saniales) [reply mongobin/getOrDownload.go]: Can you add the refactor of return values in the PR? After that i will merge

**Review by saniales — APPROVED** [review]
